#!/bin/bash
#
# Aim:
#    This code will print MJy/sr to Jy/pixel conversion factor
# 
# Usage:
#    source '/Users/dzliu/Cloud/Github/SpireLines/Softwares/bin_setup.bash'
#    FTS_tool_print_MJy_sr_to_Jy_pixel_conversion_factor "SPIRE_250um.fits"
# 


Usage() {
    echo "Usage: "
    echo "    FTS_tool_print_MJy_sr_to_Jy_pixel_conversion_factor \"SPIRE_250um.fits\" [flux_MJy_sr]"
    echo ""
}


if [[ $(type ${BASH_SOURCE[0]} 2>/dev/null | wc -l) -eq 0 ]]; then
    source $(dirname ${BASH_SOURCE[0]})/bin_setup.bash
fi

if [[ $# -eq 0 ]]; then
    Usage
    exit
fi

pix_scale=$(pixscale "$1")

if [[ $# -ge 2 ]]; then
    flux_input="$2"
else
    flux_input="1.0"
fi

awk "BEGIN {printf \"%0.20f\n\", $flux_input * (2.350443e-5 * $pix_scale * $pix_scale)}"




