#!/bin/bash
#
# Aim:
#    This code will print MJy/sr to Jy/pixel conversion factor
# 
# Usage:
#    source '/Users/dzliu/Cloud/Github/SpireLines/Softwares/bin_setup.bash'
#    FTS_tool_print_MJy_sr_to_Jy_pixel_conversion_factor "SPIRE_250um.fits"
# 


Usage() {
    echo "Usage: "
    echo "    FTS_tool_convolve_fits_image \"SPIRE_250um.fits\" -from GaussianBeam -to GaussianBeam"
    echo "    FTS_tool_convolve_fits_image \"SPIRE_250um.fits\" -from 1.4 -to 2.8 -out aaa.fits"
    echo ""
}


if [[ $(type ${BASH_SOURCE[0]} 2>/dev/null | wc -l) -eq 0 ]]; then
    source $(dirname ${BASH_SOURCE[0]})/bin_setup.bash
fi



# 
# Read user input
# 

input_fits_files=()
input_from_beam="0"
input_to_beam="0"
output_fits_files=()

i=1

while [[ $i -le $# ]]; do
    str_arg=$(echo "${!i}" | sed -e 's/^--/-/g' | tr '[:upper:]' '[:lower:]')
    if [[ "$str_arg" == "-from" ]]; then
        if [[ $(bc <<< "$i+1") -le $# ]]; then
            i=$(bc <<< "$i+1")
            input_from_beam="${!i}"
        fi
    elif [[ "$str_arg" == "-to" ]]; then
        if [[ $(bc <<< "$i+1") -le $# ]]; then
            i=$(bc <<< "$i+1")
            input_to_beam="${!i}"
        fi
    elif [[ "$str_arg" == "-out" ]]; then
        if [[ $(bc <<< "$i+1") -le $# ]]; then
            i=$(bc <<< "$i+1")
            output_fits_files+=("${!i}")
        fi
    else
        input_fits_files+=("${!i}")
    fi
    i=$(bc <<< "$i+1")
done



if [[ ${#input_fits_files[@]} -eq 0 ]] || ( [[ x"$input_from_beam" == x"0" ]] && [[ x"$input_to_beam" == x"0" ]] ); then
    Usage
    exit
fi


# 
# Run IDL code
# 
IDL_PATH="$IDL_PATH:$(dirname ${BASH_SOURCE[0]}):+$(dirname ${BASH_SOURCE[0]})/IDLAstro/pro"
echo "IDL_PATH=$IDL_PATH"
for (( i = 0; i < ${#input_fits_files[@]}; i++ )); do
if [[ $i -lt ${#output_fits_files[@]} ]]; then
    output_file="${output_fits_files[i]}"
else
    output_file=""
fi
idl -quiet << EOF
    .r FTS_tool_convolve_fits_image_idl
    FTS_tool_convolve_fits_image_idl, '${input_fits_files[i]}', from_beam=$input_from_beam, to_beam=$input_to_beam, output_file='$output_file'
EOF
done















