#!/bin/bash
#
# Aim:
#    This code will print MJy/sr to Jy/pixel conversion factor
# 
# Usage:
#    source '/Users/dzliu/Cloud/Github/SpireLines/Softwares/bin_setup.bash'
#    FTS_tool_print_MJy_sr_to_Jy_pixel_conversion_factor "SPIRE_250um.fits"
# 


Usage() {
    echo "Usage: "
    echo "    FTS_tool_regrid_fits_image \"SPIRE_250um.fits\" -x 105 -y 105"
    echo ""
}


if [[ $(type ${BASH_SOURCE[0]} 2>/dev/null | wc -l) -eq 0 ]]; then
    source $(dirname ${BASH_SOURCE[0]})/bin_setup.bash
fi



# 
# Read user input
# 

input_fits_files=()
input_to_dimension_x="0"
input_to_dimension_y="0"

i=1

while [[ $i -le $# ]]; do
    str_arg=$(echo "${!i}" | sed -e 's/^--/-/g' | tr '[:upper:]' '[:lower:]')
    if [[ "$str_arg" == "-x" ]]; then
        if [[ $(bc <<< "$i+1") -le $# ]]; then
            i=$(bc <<< "$i+1")
            input_to_dimension_x="${!i}"
        fi
    elif [[ "$str_arg" == "-y" ]]; then
        if [[ $(bc <<< "$i+1") -le $# ]]; then
            i=$(bc <<< "$i+1")
            input_to_dimension_y="${!i}"
        fi
    else
        input_fits_files+=("${!i}")
    fi
    i=$(bc <<< "$i+1")
done



if [[ ${#input_fits_files[@]} -eq 0 ]] || ( [[ x"$input_to_dimension_x" == x"0" ]] && [[ x"$input_to_dimension_y" == x"0" ]] ); then
    Usage
    exit
fi


# 
# Run IDL code
# 
IDL_PATH="$IDL_PATH:+$(dirname ${BASH_SOURCE[0]})"
for (( i = 0; i < ${#input_fits_files[@]}; i++ )); do
idl -quiet << EOF
    .r FTS_tool_regrid_fits_image
    FTS_tool_regrid_fits_image, "${input_fits_files[i]}", x=$input_to_dimension_x, y=$input_to_dimension_y
EOF
done















