#!/bin/bash
#
# Aim:
#    This code will rotate a fits image using IDL
# 
# Usage:
#    source '/Users/dzliu/Cloud/Github/SpireLines/Softwares/bin_setup.bash'
#    FTS_tool_print_MJy_sr_to_Jy_pixel_conversion_factor "SPIRE_250um.fits"
# 


Usage() {
    echo "Usage: "
    echo "    FTS_tool_rotate_fits_image \"SPIRE_250um.fits\" -angle 150 [-out output_file.fits]"
    echo "Note:"
    echo "    Clock-wise is positive angle."
    echo ""
}


if [[ $(type ${BASH_SOURCE[0]} 2>/dev/null | wc -l) -eq 0 ]]; then
    source $(dirname ${BASH_SOURCE[0]})/bin_setup.bash
fi



# 
# Read user input
# 

input_fits_files=()
input_angle="0"
output_fits_file=()

i=1

while [[ $i -le $# ]]; do
    str_arg=$(echo "${!i}" | sed -e 's/^--/-/g' | tr '[:upper:]' '[:lower:]')
    if [[ "$str_arg" == "-angle" ]]; then
        if [[ $(bc <<< "$i+1") -le $# ]]; then
            i=$(bc <<< "$i+1")
            input_angle="${!i}"
        fi
    elif [[ "$str_arg" == "-out" ]]; then
        if [[ $(bc <<< "$i+1") -le $# ]]; then
            i=$(bc <<< "$i+1")
            output_fits_file+=("${!i}")
        fi
    else
        input_fits_files+=("${!i}")
    fi
    i=$(bc <<< "$i+1")
done



if [[ ${#input_fits_files[@]} -eq 0 ]] || ( [[ x"$input_angle" == x"0" ]] ); then
    Usage
    exit
fi


# 
# Run IDL code
# 
IDL_PATH="$IDL_PATH:$(dirname ${BASH_SOURCE[0]}):+$(dirname ${BASH_SOURCE[0]})/IDLAstro/pro"
echo "IDL_PATH=$IDL_PATH"
for (( i = 0; i < ${#input_fits_files[@]}; i++ )); do
if [[ ${#output_fits_file[@]} -gt $i ]]; then
idl -quiet << EOF
.r FTS_tool_rotate_fits_image_idl
FTS_tool_rotate_fits_image_idl, "${input_fits_files[i]}", $input_angle, output_file='${output_fits_file[i]}'
EOF
else
idl -quiet << EOF
.r FTS_tool_rotate_fits_image_idl
FTS_tool_rotate_fits_image_idl, '${input_fits_files[i]}', $input_angle
EOF
fi
done















