#!/bin/bash
#
# Aim:
#    This code will create a series of circles on the sky representing FTS spaxel pattern
#    according to the user input RA Dec and PA. 
# 
# Usage:
#    source '/Users/dzliu/Cloud/Github/SpireLines/Softwares/bin_setup.bash'
#    FTS_tool_draw_pointing_pattern 194.0583608 56.87349764 0
# 

echo "TODO"





