#!/bin/bash
#
# Aim:
#    This code will try to download SPIRE photos from Herschel Science Archive (HSA)
# 
# Usage:
#    source '/Users/dzliu/Cloud/Github/SpireLines/Softwares/bin_setup.bash'
#    HSA_tool_download_SPIRE_photos
# 


# See HSA documentation:
# Herschel Archive Command Line Access: http://archives.esac.esa.int/hsa/archive-help/cl/
# http://archives.esac.esa.int/hsa/archive-help/cl/product_access/product_access.html

if [[ $# -eq 0 ]]; then
    echo "Usage: "
    echo "    HSA_tool_download_SPIRE_photos 13422100010 [SPIRE [LEVEL3]]"
    echo ""
    exit
fi

obsid="$1" # "1342195355"
instr="SPIRE"
level="LEVEL3"
if [[ $# -ge 2 ]]; then
    instr="$2"
fi
if [[ $# -ge 3 ]]; then
    instr="$3"
fi

outname="HSA_${obsid}_${instr}_${level}.tar.gz"
curl "http://archives.esac.esa.int/hsa/whsa-tap-server/data?retrieval_type=STANDALONE&observation_id=${obsid}&instrument_name=${instr}&level=${level}&compress=true" > "${outname}"


# User-provided Data Product (e.g., results from large program working groups)
outname="HSA_${obsid}_${instr}_${level}_UPDP.tar.gz"
curl "http://archives.esac.esa.int/hsa/whsa-tap-server/data?retrieval_type=UPDP&observation_id=${obsid}&instrument_name=${instr}&level=${level}&compress=true" > "${outname}"





